name : main

on:
  push:
    branches: [ main ]

jobs:
  builds:
    runs-on: ubuntu-latest

    steps:
      - name: checkout the repo
        uses: s4u/setup-maven-action@v1.2.1
        with:
          checkout-fetch-depth: 0
          java-version: 17
          maven-version: 3.8.6
      - name: build the job
        id: btj
        run: |
          mvn clean install

      - name: running the jar file
        id : rtjf
        run : |
          cp ${{ github.workspace }}/target/demo-0.0.1-SNAPSHOT.jar ${{ github.workspace }}/demo-0.0.1-SNAPSHOT.jar 
          ls -ltr
          java -jar demo-0.0.1-SNAPSHOT.jar &

      - name: terminating the jar file
        id: ttjf
        run: |
          pkill -f "demo-0.0.1-SNAPSHOT.jar" || echo "process not found"
#          to kill the process full command line


